# Generated by Django 3.0.3 on 2023-10-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('movie', models.FileField(upload_to='video/%y')),
                ('poster', models.FileField(blank=True, upload_to='poster/%y')),
                ('image', models.FileField(blank=True, upload_to='FrontImage/%y')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.Category')),
            ],
        ),
    ]
