# Generated by Django 4.2.5 on 2023-10-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
        migrations.AlterField(
            model_name='video',
            name='movie',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.URLField(blank=True),
        ),
    ]
