# Generated by Django 4.2.5 on 2023-10-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_video_image_alter_video_movie_alter_video_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='movie',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.URLField(blank=True),
        ),
    ]
