# Generated by Django 4.2.5 on 2023-10-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_alter_video_image_alter_video_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(blank=True, upload_to='FrontImage/%y'),
        ),
        migrations.AlterField(
            model_name='video',
            name='movie',
            field=models.FileField(upload_to='video/%y'),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.FileField(blank=True, upload_to='poster/%y'),
        ),
    ]
