# Generated by Django 4.2.5 on 2023-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_category_images_alter_video_image_alter_video_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.TextField(default='Default Details'),
        ),
    ]
