# Generated by Django 4.2.5 on 2023-11-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_category_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('title',)},
        ),
    ]
