# Generated by Django 4.2.5 on 2023-10-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_category_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='movieWebm',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
